#ifndef SPECTRA_SDK_NEURAL_FIELD_LAYOUT_H
#define SPECTRA_SDK_NEURAL_FIELD_LAYOUT_H

#define SPECTRA_NEURAL_FIELD_LEVEL_COUNT 8u
#define SPECTRA_NEURAL_FIELD_FEATURE_COUNT 4u
#define SPECTRA_NEURAL_FIELD_HASH_GRID_ENTRY_COUNT 2920448u
#define SPECTRA_NEURAL_FIELD_GRID_OFFSET_0 0u
#define SPECTRA_NEURAL_FIELD_GRID_OFFSET_1 4096u
#define SPECTRA_NEURAL_FIELD_GRID_OFFSET_2 36864u
#define SPECTRA_NEURAL_FIELD_GRID_OFFSET_3 299008u
#define SPECTRA_NEURAL_FIELD_GRID_OFFSET_4 823296u
#define SPECTRA_NEURAL_FIELD_GRID_OFFSET_5 1347584u
#define SPECTRA_NEURAL_FIELD_GRID_OFFSET_6 1871872u
#define SPECTRA_NEURAL_FIELD_GRID_OFFSET_7 2396160u
#define SPECTRA_NEURAL_FIELD_GRID_OFFSET_8 2920448u
#define SPECTRA_NEURAL_FIELD_DENSITY_INPUT_ROWS 64u
#define SPECTRA_NEURAL_FIELD_DENSITY_INPUT_COLUMNS 32u
#define SPECTRA_NEURAL_FIELD_DENSITY_OUTPUT_ROWS 16u
#define SPECTRA_NEURAL_FIELD_DENSITY_OUTPUT_COLUMNS 64u
#define SPECTRA_NEURAL_FIELD_RGB_INPUT_ROWS 64u
#define SPECTRA_NEURAL_FIELD_RGB_INPUT_COLUMNS 32u
#define SPECTRA_NEURAL_FIELD_RGB_HIDDEN_ROWS 64u
#define SPECTRA_NEURAL_FIELD_RGB_HIDDEN_COLUMNS 64u
#define SPECTRA_NEURAL_FIELD_RGB_OUTPUT_ROWS 16u
#define SPECTRA_NEURAL_FIELD_RGB_OUTPUT_COLUMNS 64u
#define SPECTRA_NEURAL_FIELD_OCCUPANCY_RESOLUTION 128u
#define SPECTRA_NEURAL_FIELD_OCCUPANCY_WORD_COUNT (SPECTRA_NEURAL_FIELD_OCCUPANCY_RESOLUTION * SPECTRA_NEURAL_FIELD_OCCUPANCY_RESOLUTION * SPECTRA_NEURAL_FIELD_OCCUPANCY_RESOLUTION / 32u)

#ifdef __cplusplus
#include <array>
#include <cstdint>

namespace spectra::sdk::neural_field_layout {
    inline constexpr std::uint32_t level_count          = SPECTRA_NEURAL_FIELD_LEVEL_COUNT;
    inline constexpr std::uint32_t feature_count        = SPECTRA_NEURAL_FIELD_FEATURE_COUNT;
    inline constexpr std::uint32_t hash_grid_entry_count = SPECTRA_NEURAL_FIELD_HASH_GRID_ENTRY_COUNT;
    inline constexpr std::array<std::uint32_t, level_count + 1u> grid_offsets{
        SPECTRA_NEURAL_FIELD_GRID_OFFSET_0,
        SPECTRA_NEURAL_FIELD_GRID_OFFSET_1,
        SPECTRA_NEURAL_FIELD_GRID_OFFSET_2,
        SPECTRA_NEURAL_FIELD_GRID_OFFSET_3,
        SPECTRA_NEURAL_FIELD_GRID_OFFSET_4,
        SPECTRA_NEURAL_FIELD_GRID_OFFSET_5,
        SPECTRA_NEURAL_FIELD_GRID_OFFSET_6,
        SPECTRA_NEURAL_FIELD_GRID_OFFSET_7,
        SPECTRA_NEURAL_FIELD_GRID_OFFSET_8,
    };
    inline constexpr std::array<std::array<std::uint32_t, 2>, 5> matrix_dimensions{{
        {SPECTRA_NEURAL_FIELD_DENSITY_INPUT_ROWS, SPECTRA_NEURAL_FIELD_DENSITY_INPUT_COLUMNS},
        {SPECTRA_NEURAL_FIELD_DENSITY_OUTPUT_ROWS, SPECTRA_NEURAL_FIELD_DENSITY_OUTPUT_COLUMNS},
        {SPECTRA_NEURAL_FIELD_RGB_INPUT_ROWS, SPECTRA_NEURAL_FIELD_RGB_INPUT_COLUMNS},
        {SPECTRA_NEURAL_FIELD_RGB_HIDDEN_ROWS, SPECTRA_NEURAL_FIELD_RGB_HIDDEN_COLUMNS},
        {SPECTRA_NEURAL_FIELD_RGB_OUTPUT_ROWS, SPECTRA_NEURAL_FIELD_RGB_OUTPUT_COLUMNS},
    }};
    inline constexpr std::uint32_t occupancy_resolution = SPECTRA_NEURAL_FIELD_OCCUPANCY_RESOLUTION;
    inline constexpr std::uint32_t occupancy_word_count = SPECTRA_NEURAL_FIELD_OCCUPANCY_WORD_COUNT;
} // namespace spectra::sdk::neural_field_layout
#endif

#endif
