#ifndef SPECTRA_PATHTRACER_UTIL_CHECK_H
#define SPECTRA_PATHTRACER_UTIL_CHECK_H

#include <pathtracer/core/diagnostics.cuh>

#define CHECK(EXPR)    SPECTRA_CHECK(EXPR)
#define CHECK_EQ(A, B) SPECTRA_CHECK_EQ(A, B)
#define CHECK_NE(A, B) SPECTRA_CHECK_NE(A, B)
#define CHECK_GT(A, B) SPECTRA_CHECK_GT(A, B)
#define CHECK_GE(A, B) SPECTRA_CHECK_GE(A, B)
#define CHECK_LT(A, B) SPECTRA_CHECK_LT(A, B)
#define CHECK_LE(A, B) SPECTRA_CHECK_LE(A, B)

#endif // SPECTRA_PATHTRACER_UTIL_CHECK_H
