#ifndef SPECTRA_PATHTRACER_UTIL_CHECK_H
#define SPECTRA_PATHTRACER_UTIL_CHECK_H

#include <spectra/pathtracer/core/diagnostics.cuh>

#define CHECK(EXPR)    SPECTRA_CHECK(EXPR)
#define CHECK_EQ(A, B) SPECTRA_CHECK_EQ(A, B)
#define CHECK_NE(A, B) SPECTRA_CHECK_NE(A, B)
#define CHECK_GT(A, B) SPECTRA_CHECK_GT(A, B)
#define CHECK_GE(A, B) SPECTRA_CHECK_GE(A, B)
#define CHECK_LT(A, B) SPECTRA_CHECK_LT(A, B)
#define CHECK_LE(A, B) SPECTRA_CHECK_LE(A, B)

#define DCHECK(EXPR)    SPECTRA_DCHECK(EXPR)
#define DCHECK_EQ(A, B) SPECTRA_DCHECK_EQ(A, B)
#define DCHECK_NE(A, B) SPECTRA_DCHECK_NE(A, B)
#define DCHECK_GT(A, B) SPECTRA_DCHECK_GT(A, B)
#define DCHECK_GE(A, B) SPECTRA_DCHECK_GE(A, B)
#define DCHECK_LT(A, B) SPECTRA_DCHECK_LT(A, B)
#define DCHECK_LE(A, B) SPECTRA_DCHECK_LE(A, B)

#define CHECK_RARE(FREQ, CONDITION)  ((void) 0)
#define DCHECK_RARE(FREQ, CONDITION) ((void) 0)

#endif // SPECTRA_PATHTRACER_UTIL_CHECK_H
