include_guard(GLOBAL)

set(CACHE{GLFW_BUILD_DOCS} TYPE INTERNAL HELP "Build GLFW documentation" FORCE VALUE OFF)
set(CACHE{GLFW_BUILD_EXAMPLES} TYPE INTERNAL HELP "Build GLFW examples" FORCE VALUE OFF)
set(CACHE{GLFW_BUILD_TESTS} TYPE INTERNAL HELP "Build GLFW tests" FORCE VALUE OFF)
set(CACHE{GLFW_INSTALL} TYPE INTERNAL HELP "Generate GLFW installation target" FORCE VALUE OFF)

FetchContent_MakeAvailable(glfw)
