include_guard(GLOBAL)

set(TBB_TEST OFF CACHE BOOL "" FORCE)
set(TBB_EXAMPLES OFF CACHE BOOL "" FORCE)
set(TBB_STRICT OFF CACHE BOOL "" FORCE)
unset(TBB_DIR CACHE)
set(CMAKE_POLICY_VERSION_MINIMUM 3.5)
set(BUILD_SHARED_LIBS ON)
set(CMAKE_CXX_MODULE_STD OFF)
FetchContent_MakeAvailable(onetbb)
set(CMAKE_CXX_MODULE_STD ON)
unset(BUILD_SHARED_LIBS)
unset(CMAKE_POLICY_VERSION_MINIMUM)

if (NOT TARGET TBB::tbb)
    add_library(TBB::tbb ALIAS tbb)
endif ()

set(SPECTRA_TBB_CONFIG_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/vendor/tbb")
file(MAKE_DIRECTORY "${SPECTRA_TBB_CONFIG_DIRECTORY}")
file(
        WRITE "${SPECTRA_TBB_CONFIG_DIRECTORY}/TBBConfig.cmake"
        "set(TBB_FOUND TRUE)\nset(TBB_VERSION 2021.9.0)\n"
)
file(
        WRITE "${SPECTRA_TBB_CONFIG_DIRECTORY}/TBBConfigVersion.cmake"
        "set(PACKAGE_VERSION 2021.9.0)\nif (PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)\n    set(PACKAGE_VERSION_COMPATIBLE FALSE)\nelse ()\n    set(PACKAGE_VERSION_COMPATIBLE TRUE)\nendif ()\nif (PACKAGE_FIND_VERSION STREQUAL PACKAGE_VERSION)\n    set(PACKAGE_VERSION_EXACT TRUE)\nendif ()\n"
)
set(TBB_DIR "${SPECTRA_TBB_CONFIG_DIRECTORY}" CACHE PATH "" FORCE)
