include("${CMAKE_CURRENT_LIST_DIR}/DependencyAcquisition.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/dependencies/Vulkan.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/dependencies/Slang.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/dependencies/Xcli.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/dependencies/Ckdl.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/dependencies/Lodepng.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/dependencies/Tinyexr.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/dependencies/NanoVDB.cmake")

if (SPECTRA_BUILD_UI)
    include("${CMAKE_CURRENT_LIST_DIR}/dependencies/Glfw.cmake")
    include("${CMAKE_CURRENT_LIST_DIR}/dependencies/ImGui.cmake")
    include("${CMAKE_CURRENT_LIST_DIR}/dependencies/ImGuizmo.cmake")
endif ()
