function(spectra_append_spirv_array output variable input)
    file(READ "${input}" spirv_hex HEX)
    string(LENGTH "${spirv_hex}" spirv_hex_length)
    math(EXPR spirv_byte_length "${spirv_hex_length} / 2")
    if (NOT spirv_hex_length GREATER 0)
        message(FATAL_ERROR "SPIR-V input is empty: ${input}")
    endif ()
    math(EXPR spirv_remainder "${spirv_byte_length} % 4")
    if (NOT spirv_remainder EQUAL 0)
        message(FATAL_ERROR "SPIR-V input byte length is not divisible by 4: ${input}")
    endif ()
    math(EXPR spirv_word_count "${spirv_byte_length} / 4")
    string(APPEND "${output}" "alignas(4) inline constexpr std::array<std::uint32_t, ${spirv_word_count}> ${variable}{\n")
    math(EXPR spirv_last_word "${spirv_word_count} - 1")
    foreach (word_index RANGE 0 ${spirv_last_word})
        math(EXPR hex_offset "${word_index} * 8")
        string(SUBSTRING "${spirv_hex}" ${hex_offset} 2 byte0)
        math(EXPR hex_offset "${hex_offset} + 2")
        string(SUBSTRING "${spirv_hex}" ${hex_offset} 2 byte1)
        math(EXPR hex_offset "${hex_offset} + 2")
        string(SUBSTRING "${spirv_hex}" ${hex_offset} 2 byte2)
        math(EXPR hex_offset "${hex_offset} + 2")
        string(SUBSTRING "${spirv_hex}" ${hex_offset} 2 byte3)
        string(APPEND "${output}" "    0x${byte3}${byte2}${byte1}${byte0}u,\n")
    endforeach ()
    string(APPEND "${output}" "};\n")
    string(APPEND "${output}" "inline constexpr std::size_t ${variable}_size = ${variable}.size() * sizeof(std::uint32_t);\n\n")
    set("${output}" "${${output}}" PARENT_SCOPE)
endfunction()

set(header_contents "#pragma once\n#include <array>\n#include <cstddef>\n#include <cstdint>\n\nnamespace xayah::generated {\n")
spectra_append_spirv_array(header_contents spectra_raster_vertex_spirv "${VERTEX_INPUT}")
spectra_append_spirv_array(header_contents spectra_raster_fragment_spirv "${FRAGMENT_INPUT}")
string(APPEND header_contents "} // namespace xayah::generated\n")
file(WRITE "${OUTPUT}" "${header_contents}")
